### PR TITLE
Add N2V SEM Demo model

### PR DESCRIPTION
**Pull request by frauzufall**

### CODE REVIEW

**Comment by oeway** [comment]
Looks good to me.

**Comment by oeway** [comment]
In order to make the Fiji BioEngine app work, we need a bit more works. Do you by chance have a macro that runs the model with your test input data in a headless mode? Then we can use PyImageJ to run that.

**Comment by frauzufall** [comment]
Can it also be a jython / groovy script?

**Comment by oeway** [comment]
Yes, any script that can run by Fiji.

**Comment by oeway** [comment]
Will merge this for now.

**Pull request merged**
