### PR TITLE
Add 2D U-Net trained to predict boundaries in Arabidopsis ovules

### PR DESCRIPTION
**Pull request by wolny**
TODO:
- [ ] make sure the model works in ilastik

### CODE REVIEW

**Comment by oeway** [comment]
Hi, looks good to me.

FYI: we made some changes to the configuration format, see here https://github.com/bioimage-io/configuration/pull/24
And there are two related PR not merged.

I think we can merge this for now,  it we may ask you to change according to the new format later.

**Comment by wolny** [comment]
Hey @oeway. Yes, I have another PR ready which reflects the changes to to the config format, but we would like to have this merged in first for the deep ilastik demo. This is WIP so please do not merge it yet.

**Comment by oeway** [comment]
@wolny FYI: I have just made some changes to the yaml manifest file format, see example here: https://github.com/bioimage-io/bioimage-io-models/blob/master/src/manifest.bioimage.io.yaml#L28-L32

**Comment by constantinpape** [comment]
We should add this to https://github.com/ilastik/bioimage-io-models instead; the ilastik models will be pulled in from there once we merge #38

**Comment by oeway** [comment]
Should we close this PR? @wolny 

The migration has been completed, please send your PR to the ilastik repo: https://github.com/ilastik/bioimage-io-models

**Comment by wolny** [comment]
yes @oeway, this should be closed. Thx!

**Pull request closed without merging**
