### PR TITLE
Update 3D UNet Arabidopsis ovules model description

### PR DESCRIPTION
**Pull request by wolny**
CC @FynnBe, @vzinche

### CODE REVIEW

**Comment by FynnBe** [comment]
this change will be lost once the json is recreated by the script. Don't you want to change it in the model.yaml?

**Comment by wolny** [comment]
yes, this has been changed in the https://github.com/wolny/pytorch-3dunet/blob/master/bioimage-io/UNet3DArabidopsisOvules.model/UNet3DArabidopsisOvules.model.yam as well

**Comment by oeway** [comment]
Right, actually, you only need to change the yaml, I added a CO script to generate the json and serve it with GitHub pages.

BYW,I added a new contribution guideline. Could you please take a look and see if that works? https://bioimage.io/#/?show=contribute

**Comment by oeway** [comment]
So in this case, you don’t need a PR, update the yaml config on your side then it will be updates by CI script that runs every two hours.

**Comment by wolny** [comment]
Thanks for info @oeway. This is indeed how it should be done. As mentioned the description was updated in the YAML file in the original repo, but I still need a PR here to point to the new YAML source. Let's merge this one when the tests are green.

**Comment by wolny** [comment]
@oeway  Any ideas why the tests are failing?
They fail when the following item is being parsed:
```
{'id': 'dummy-dataset', 'name': 'Dummy Zarr', 'description': 'A dummy zarr dataset', 'cite': None, 'authors': [], 'documentation': None, 'tags': ['zarr'], 'attachments': {'files': ['https://gist.githubusercontent.com/manzt/d16dbac0ea3adc3c7b9b61f54fa1f78d/raw/95854058512862accb0182d4a02f86a55ad19139/', 'https://gist.githubusercontent.com/manzt/d16dbac0ea3adc3c7b9b61f54fa1f78d/raw/95854058512862accb0182d4a02f86a55ad19139/']}}
```

however I don't see it in the `manifest.bioimage.io.yaml`

**Comment by oeway** [comment]
Sorry, I broke it. I am on it.

**Comment by oeway** [comment]
@wolny could you rebase your branch? And try it again, I just fixed it.

**Comment by wolny** [comment]
@oeway by merging the master into my branch, my changes were overwritten and got lost.

**Comment by oeway** [comment]
Sorry and thanks for the new PR.

**Pull request merged**
